name: qrcard
description: "A new Flutter project"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  qr_flutter: ^4.1.0
  image_picker: ^1.0.7
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  http: ^1.1.2
  device_info_plus: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
